CREATE DATABASE IF NOT EXISTS mydb_sensorss;

USE mydb_sensorss;

-- DROP TABLE IS EXIST site1;

CREATE TABLE site1 (
    id          INT PRIMARY KEY AUTOINCREMENT UNIQUE,
    sitename    VARCHAR(20) DEFAULT NULL,
    email       VARCHAR(255) DEFAULT NULL,
    Timestamp   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TEMPERATURE FLOAT DEFAULT NULL,
    WINDSPEED   VARCHAR(255) DEFAULT NULL
    CONSTRAINT UQ_site1_Email UNIQUE (email)
)

-- for docker only